export const PROVINCIAS = [
  { "id": "15", "nombre": "A Coruña" },
  { "id": "01", "nombre": "Álava" },
  { "id": "02", "nombre": "Albacete" },
  { "id": "03", "nombre": "Alicante" },
  { "id": "04", "nombre": "Almería" },
  { "id": "33", "nombre": "Asturias" },
  { "id": "05", "nombre": "Ávila" },
  { "id": "06", "nombre": "Badajoz" },
  { "id": "08", "nombre": "Barcelona" },
  { "id": "48", "nombre": "Bizkaia" },
  { "id": "09", "nombre": "Burgos" },
  { "id": "10", "nombre": "Cáceres" },
  { "id": "11", "nombre": "Cádiz" },
  { "id": "39", "nombre": "Cantabria" },
  { "id": "12", "nombre": "Castellón" },
  { "id": "51", "nombre": "Ceuta" },
  { "id": "13", "nombre": "Ciudad Real" },
  { "id": "14", "nombre": "Córdoba" },
  { "id": "16", "nombre": "Cuenca" },
  { "id": "20", "nombre": "Gipuzkoa" },
  { "id": "17", "nombre": "Girona" },
  { "id": "18", "nombre": "Granada" },
  { "id": "19", "nombre": "Guadalajara" },
  { "id": "21", "nombre": "Huelva" },
  { "id": "22", "nombre": "Huesca" },
  { "id": "07", "nombre": "Illes Balears" },
  { "id": "23", "nombre": "Jaén" },
  { "id": "26", "nombre": "La Rioja" },
  { "id": "35", "nombre": "Las Palmas" },
  { "id": "24", "nombre": "León" },
  { "id": "25", "nombre": "Lleida" },
  { "id": "27", "nombre": "Lugo" },
  { "id": "28", "nombre": "Madrid" },
  { "id": "29", "nombre": "Málaga" },
  { "id": "52", "nombre": "Melilla" },
  { "id": "30", "nombre": "Murcia" },
  { "id": "31", "nombre": "Navarra" },
  { "id": "32", "nombre": "Ourense" },
  { "id": "34", "nombre": "Palencia" },
  { "id": "36", "nombre": "Pontevedra" },
  { "id": "37", "nombre": "Salamanca" },
  { "id": "38", "nombre": "Santa Cruz de Tenerife" },
  { "id": "40", "nombre": "Segovia" },
  { "id": "41", "nombre": "Sevilla" },
  { "id": "42", "nombre": "Soria" },
  { "id": "43", "nombre": "Tarragona" },
  { "id": "44", "nombre": "Teruel" },
  { "id": "45", "nombre": "Toledo" },
  { "id": "46", "nombre": "Valencia" },
  { "id": "47", "nombre": "Valladolid" },
  { "id": "49", "nombre": "Zamora" },
  { "id": "50", "nombre": "Zaragoza" }
];